title: zerokhha's Blog
logo_img: 
favicon:
description: 배움과 기록을 위한 공간
global_tags: jekyll, blog, dev, github-pages
copyright: © zerokhha 2026

sass:
    style: compressed

collections:
    category:
        output: true
        permalink: /category/:name/
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"